### ISSUE TITLE
Custom plots based on borehole selection on the map

### ISSUE THREAD

**Issue by Robel756** [jkall/qgis-midvatten-plugin#104]
Hi Josef, 
May I suggest if there could be a way of plotting custom figures based on selected boreholes on the map, instead of selecting the boreholes from the custom list. 
Thanks for the impressive work.

**Comment by HenrikSpa** [comment]
This is implemented now in the postgis branch. It's needed due to the large amount of obspoint in the same database.

How:
Pressing the new button (one for each filter) will select items in the list based on the selected items in the selected layer that have the same column name as the filter column.

Ex: choosing obsid as filter, one can select rows in any layer that also have the column obsid (obs_points, w_levels etc.)
This can be done for any colum, not just obsid.
