### ISSUE TITLE
Query - Python versions

### ISSUE THREAD

**Issue by mikesumbler** [jkall/qgis-midvatten-plugin#343]
Hi, 

May have missed it - is this plugin compatible with Python 3 (specifically version 3.10.7) 

Looks amazing.

Kind Regards
Mike

**Comment by mikesumbler** [comment]
Apologises - found the update to Python 3 in your changelog as of v 1.6

Could I check also - matplot backends. The wiki may be a little outdated, is QtAgg the replacement for Qt4Agg? 

Many Thanks
Mike

**Comment by HenrikSpa** [comment]
Hi! Yes as you wrote, it's compatible with QGIS 3. There are some minor bugs introduced by QGIS 3.22 that will be fixed in the next Midvatten version. 

And yes, the "Installation" page on the wiki is extremely outdated and should not be followed at all! I will update it, but until then:

If using Windows, install QGIS 3.22 using the OSGeo4W network installer.(https://www.qgis.org/en/site/forusers/download.html). I have not tested 3.28 yet so there might be compatibility issues with that one.

Choose Advanced install, and when at "Select Packages", choose to install Desktop>qgis-ltr version 3.22.x (latest)
Also search for pandas and install package Libs>python3-pandas as the Midvatten plugin use that a lot.

Open QGIS and install plugin Midvatten using the QGIS plugin menu.

Regards,
Henrik

**Comment by mikesumbler** [comment]
Thank you.
