### ISSUE TITLE
Can't add obs_points

### ISSUE THREAD

**Issue by User-1a** [jkall/qgis-midvatten-plugin#349]
I've got a database set up and added the default layers to my project but I can't add new obs_points. I toggled editing on that layer and clicked on a location to add a point but when the Feature Attributes window pops up the OK button is greyed out. I thought only the obsid was required, so I tried putting data in every field but it was still greyed out. I checked the permissions on the sqlite database file (I'm using Windows 10) and made sure my user had read/write/modify permission and restarted QGIS but I still can't add features to the obs_points layer. Am I missing something? I can edit other layers I created in this project. Any help/suggestions would be much appreciated!

**Comment by HenrikSpa** [comment]
Hi!
What's your version of QGIS and Midvatten plugin?

**Comment by User-1a** [comment]
Hi,
I'm using QGIS 3.28.6-Firenze and the Midvatten plugin is 1.7.3

**Comment by HenrikSpa** [comment]
This error seem to appear and disappear with different QGIS versions. I think the problem happens because there is three entries for "obsid".

Here is a short solution (until next Midvatten plugin version) which worked for me:

1. Open Properties-window for layer obs_points and go to Attributes form:
![image](https://github.com/jkall/qgis-midvatten-plugin/assets/17615137/85989544-3a22-4a77-8ec2-b76d73369a3f)
2. In the form layout section, open "general" and "observation point".  Drag "obsid" to the top above section "general"
![image](https://github.com/jkall/qgis-midvatten-plugin/assets/17615137/eb7a73c9-a654-4971-8c47-47b2a9bf2c16)
3. Open sections "general", "xyz" and "management", mark the groups named "observations points" and click the remove button.
![image](https://github.com/jkall/qgis-midvatten-plugin/assets/17615137/992e571f-6b73-42ad-b7bc-4b299cadc8ef)

 Now there is only one entry for obsid, and when I added a new point and gave it an obsid I could now save it.

This is probably the solution I introduce in the next plugin version.

Regards,
Henrik

**Comment by User-1a** [comment]
Thank you Henrik! I never would have figured that out for myself. It's
working for me now.

Jono

**Comment by HenrikSpa** [comment]
Solved in version 1.7.11.
