### ISSUE TITLE
add postGIS support

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#69]
There should be an alternative to use a postGIS database instead of a spatialite dito.

**Comment by HenrikSpa** [comment]
Started working with this issue in branch postgis_henrik.
Progress so far:
* Installed postgres+postgis+pgadmin3 using the package https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-testing-deletedppa/+build/10312769
* Gone through the rows in createdb to fill a premade postgis database and made them work with postgis.
* Gone through one insert datadomain and it worked well.

**Comment by HenrikSpa** [comment]
Progress so far:
* Connection to a pre-created database is now done through Qgis own connection manager "Layer > Add Layer > Add Postgis Layer". When a connection has been made, it will be found under the new DB tab in midvatten settings dialog when selecting postgis.
* The "create db" for spatialite now has a "populate postgis" variant which populate the pre-created database will all midvatten layers.
* Load default layers adds alla layers and views just like for spatialite.

Todo:
* Test/adjust all midvatten features one at the time with both postgis and spatialite and make adjustments where needed.

How it's done:
* Lot's and lot's of refactoring so that the code works in a unified way for both databases with a minimum of "if postgis" and "if spatialite" sections. I've used it in some places though.

**Comment by HenrikSpa** [comment]
The postgis branch is now a fully functional beta version. Some bugs will surely appear but it seems to be working nicely.

**Comment by HenrikSpa** [comment]
Getting postgis working was much easier in Linux miny 18.2 compared to the hassle I had in 17.3.

**Comment by jkall** [comment]
implemented in version 1.5
